/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#732ee4",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0f0069",
        "inverse-primary": "#d2bbff",
        "on-secondary-fixed-variant": "#3323cc",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed": "#ffdcc6",
        "surface-variant": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "secondary": "#4b41e1",
        "tertiary-container": "#a15100",
        "outline-variant": "#ccc3d8",
        "tertiary": "#7d3d00",
        "inverse-surface": "#283044",
        "secondary-fixed": "#e2dfff",
        "outline": "#7b7487",
        "primary": "#630ed4",
        "on-tertiary-fixed": "#301400",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed-variant": "#5a00c6",
        "on-tertiary-container": "#ffe0cd",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-background": "#131b2e",
        "on-secondary": "#ffffff",
        "background": "#faf8ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "surface-bright": "#faf8ff",
        "surface-container": "#eaedff",
        "on-primary-container": "#ede0ff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#4a4455",
        "tertiary-fixed-dim": "#ffb784",
        "surface": "#faf8ff",
        "primary-fixed-dim": "#d2bbff",
        "inverse-on-surface": "#eef0ff",
        "on-error-container": "#93000a",
        "on-surface": "#131b2e",
        "on-primary-fixed": "#25005a",
        "secondary-fixed-dim": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#7c3aed",
        "on-tertiary-fixed-variant": "#713700",
        "primary-fixed": "#eaddff",
        "secondary-container": "#645efb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "sans-serif"],
      },
    },
  },
  plugins: [],
}
